config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'users/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :grandmasters do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :index] do
    patch :accept
    patch :reject
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :grandmaster
  belongs_to :user
  has_one :grandmaster_user, through: :grandmaster, source: :user
end

app/models/grandmaster.rb
class Grandmaster < ApplicationRecord
  # has_many :users
  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :fide_id, presence: true, uniqueness: true
  validates :elo_rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sent_bookings, dependent: :destroy, class_name: "Booking" # bookings created by the user

  has_one :grandmaster, dependent: :destroy
  has_many :received_bookings, through: :grandmaster, source: :bookings

  has_one_attached :photo

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    # @bookings = Booking.all
    # current_user
    # @bookings = Booking.find(params[:id])
    # warden.user.user.key
    @sent_bookings = current_user.sent_bookings
    @received_bookings = current_user.received_bookings
  end

  def new
    @grandmaster = Grandmaster.find(params[:grandmaster_id])
    # @user = User.find(params[:user_id])
    @booking = Booking.new
  end

  def create
    @grandmaster = Grandmaster.find(params[:grandmaster_id])
    # @user = User.find(params[:user_id])
    @booking = Booking.new(booking_params)
    @booking.grandmaster = @grandmaster
    @booking.user = current_user
    #@booking.user = @user
    if @booking.save
      redirect_to bookings_path, notice: 'Booking succesfully created'
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    @sent_bookings = current_user.sent_bookings
    @received_bookings = current_user.received_bookings

    # no need for app/views/restaurants/update.html.erb
    redirect_to bookings_path(@booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    # @list = @bookmark.list
    @booking.destroy
    redirect_to grandmaster_path(@grandmaster)
    # redirect_to user_path(@user)
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    @booking.status = "accepted"
    @booking.save
    redirect_to bookings_path
  end

  def reject
    @booking = Booking.find(params[:booking_id])
    @booking.status = "rejected"
    @booking.save
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:message, :status)
  end
end

app/controllers/grandmasters_controller.rb
class GrandmastersController < ApplicationController
  # before_action :set_user, only: %i[ show ]
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query]
      @grandmasters = Grandmaster.joins(:user).where('name ILIKE ?', "%#{params[:query]}%")
    else
      @grandmasters = Grandmaster.all
    end
  end

  def show
    @grandmaster = Grandmaster.find(params[:id])
  end

  def new
    @grandmaster = Grandmaster.new
  end

  def create
    @grandmaster = Grandmaster.new(grandmaster_params)
    @grandmaster.user = current_user
    if @grandmaster.save
      redirect_to grandmaster_path(@grandmaster)
    else
      render :new
    end
  end

  def destroy
    @destroy = Grandmaster.find(params[:id])
    @destroy.destroy
    redirect_to grandmaster_path(@grandmaster)
  end

  private

  # def set_user
  #   @user = User.find(params[:id])
  # end

  def grandmaster_params
    params.require(:grandmaster).permit(:country, :bio, :fide_id, :language, :elo_rating)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container ">
  <div class="row justify-content-center">
  <div class="col-9">
    <div class="class gm-info">
      <%= cl_image_tag @grandmaster.user.photo.key, class: "avatar-large color-white" %>
      <div class="text-center coloration">
      <p class="mt-4">Elo - <%= @grandmaster.elo_rating %> | Language: <%= @grandmaster.language.capitalize %></p>
      <p class="text-start"><%= @grandmaster.bio %></p>
      </div>
      <div class="user_form">
        <%= simple_form_for([@grandmaster, @booking]) do |f| %>
          <%= f.input :message, label_html: { class: "coloration" } %>
          <div class="d-flex justify-content-center">
            <%= f.submit class: "hero-btn"%>
          </div>
        <% end %>
        </div>
      </div>
  </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <h2 id="h2-booking-status">Bookings status</h2>
  <br>
  <br>
  <div class="row d-flex justify-content-center" id="booking-status">
    <div class="col-sm-12 col-md-8 col-lg-8">
      <% if @sent_bookings.exists? || @received_bookings.exists? %>
        <% if @sent_bookings.exists? && @received_bookings.exists? %>
          <div class="switch-holder">
            <div class="switch-label">
              <span>As a pupil</span>
            </div>
            <div class="switch-toggle">
              <input type="checkbox" id="choice">
              <label for="choice"></label>
            </div>
            <div class="switch-label">
              <span>As a Grandmaster</span>
            </div>
          </div>
          <br>
          <br>
        <% end %>
        <div id="pupil">
          <% @sent_bookings.each do |booking| %>
            <div class="booking-card">
              <% if booking.status == "rejected" %>
                <div class="rejected-card">
              <% elsif booking.status == "accepted" %>
                <div class="accepted-card">
              <% elsif booking.status == "pending" %>
                <div class="pending-card">
              <% end %>
                  Status : <%= booking.status %><br>
                </div>
              Your Grandmaster : <strong><%= booking.grandmaster_user.name %></strong><br>
              Message : <%= booking.message %><br>
            </div>
            <br>
          <% end %>
        </div>

        <div id="grandmaster">
          <% @received_bookings.each do |booking| %>
            <div class="booking-card">
              <% if booking.status == "rejected" %>
                <div class="rejected-card">
              <% elsif booking.status == "accepted" %>
                <div class="accepted-card">
              <% elsif booking.status == "pending" %>
                <div class="pending-card">
              <% end %>
                  Status : <%= booking.status %><br>
                </div>
              Your pupil : <strong><%= booking.user.name %></strong><br>
              Message : <%= booking.message %><br>
              <% if booking.status == "pending" %>
                <div class="booking-btn">
                  <%= link_to 'Accept', booking_accept_path(booking), method: "patch" %>
                </div>
                <div class="booking-btn">
                  <%= link_to 'Reject', booking_reject_path(booking), method: "patch" %>
                </div>
              <% end %>
            </div>
            <br>
          <% end %>
        </div>
      <% else %>
          You have no booking.
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container  gm-form">
  <div class="row text-center">
      <h1 class="h1-book-gm">Book <%= @grandmaster.user.name %></h1>
      <%= render 'form' %>
  </div>
</div>

app/views/grandmasters/_form.html.erb
<!-- app/views/grandmasters/_form.html.erb -->

      <%= simple_form_for(@grandmaster) do |f| %>
        <%= f.input :elo_rating %>
        <%= f.input :fide_id %>
        <%= f.input :language, collection: ['English', 'French', 'Spanish']%>
        <%= f.input :country %>
        <%= f.input :bio %>
        <div class="d-flex justify-content-center">
          <div>
            <%= f.submit class: "hero-btn" %>
          </div>
        </div>
      <% end %>

app/views/grandmasters/index.html.erb
<h1 class="text-center">Our Grandmasters</h1>
  <div class="cards-index">
    <% @grandmasters.each do |grandmaster|%>
        <%= link_to grandmaster_path(grandmaster), class: "text-decoration-none" do %>
            <div class="card">
              <% if grandmaster.user.photo.attached? %>
                <%= cl_image_tag grandmaster.user.photo.key, class: "card-image-middle avatar" %>
              <% else %>
                <img class="card-image-middle avatar" src="https://thezugzwangblog.com/wp-content/uploads/2020/07/kasparaov-1024x574.jpg" alt="Card">
              <% end %>
              <div class="card-body text-center">
                <h5 class="card-title"><%= grandmaster.user.name %></h5>
                <p class="card-text"><%= grandmaster.bio %></p>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>

app/views/grandmasters/new.html.erb
<div class="container gm-form">
  <%= image_tag 'components/Logo.png', class: "logo_new"  %>
 <h2 class = "text_form mb-3 mt-3 text-center">Create a new grandmaster profile</h2>
  <div class="row justify-content-center">

  <div class="col-sm-8 col-md-6 col-lg-6 ">
      <%# <%= image_tag 'magnus.jpg', class: "gm_image" %>
  </div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/grandmasters/show.html.erb
<h1 class="text-center"><%= @grandmaster.user.name %></h1>
  <div class="container">
    <div class="row mt-4 d-flex justify-content-around">
      <div class="gm-show-card w-75">
        <% if @grandmaster.user.photo.attached? %>
          <%= cl_image_tag @grandmaster.user.photo.key, class: "card-image-middle photo-chess" %>
        <% else %>
          <img class="card-image-middle photo-chess" src="https://thezugzwangblog.com/wp-content/uploads/2020/07/kasparaov-1024x574.jpg" alt="Card">
        <% end %>
          <div class="gm-info-container">
            <ul class="gm-info-list">
              <li><strong>Language</strong> - <%= @grandmaster.language.capitalize%></li>
              <br>
              <li><strong>Fide</strong> - <%= @grandmaster.fide_id %></li>
              <br>
              <li><strong>Country</strong> - <%= @grandmaster.country %></li>
              <br>
              <li><strong>Elo Rating</strong> - <%= @grandmaster.elo_rating %></li>
              <br>
              <li><strong>Bio</strong> - <%= @grandmaster.bio %></li>
            </ul>
            <div class="book-me-container">
              <%= link_to "Book me", new_grandmaster_booking_path(@grandmaster), class: "hero-btn ", id: "book-me-id" %>
            </div>
          </div>
          </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FIND A GRANDMASTER</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag asset_path('icons/favicon.ico') %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container home-container">
  <div class="test">
    <div class="row align-items-stretch h-100">
      <div class="col-md-6 col-sm-8 offset-md-1">
        <div class="hero-text-container">
          <h1>FIND A GRANDMASTER</h1>
            <p class="info-home-gm">You will have the opportunity of you life to meet world famous Chess Grandmasters. We have had clients such as Magnus Carlson, Lali B and millions of satisfied customers
                <br> <i>- CEO Loranzini Totolini"</i></p>
            <%= link_to "Check our Grandmasters", grandmasters_path, class: "hero-btn text-decoration-none"%>
        </div>
      </div>
        <div class="col-sm-4 h-100">
              <%= image_tag "components/home_img_2.jpg" , class: "home-image" %>
        </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon nav-button">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
    <div id="logo">
      <%= image_tag "components/Logo.svg"  %>
      </div>

</a>
<div class="topnav search-bar">
      <a class="active " href="#home"></a>
      <form action="/grandmasters" method="get" class="gm-margin">
        <input type="text" name='query' class="search" placeholder="Search.." value="<%= params[:query] %>">
        <button type="submit" class="search-button">Go</button>
      </form>
    </div>



    <button class="navbar-toggler navbar navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <% if user_signed_in? && current_user.grandmaster.nil? %>
            <li class= "nav-item">
              <%= link_to "Create your Grandmaster profile", new_grandmaster_path, class: "nav-link" %>
            </li>
          <% end %>

          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Bookings", bookings_path, class: "nav-link" %>
            </li>
          <% else %>
              <li class="nav-item active">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown nav-link">

          <%# avatar photo if it is sign in %>
           <% if user_signed_in? && current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" } %>
            <% else %>
              <%= image_tag "components/user.svg", class: "avatar avatar_2 dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" } %>
           <% end %>

          <%# sign in - sign out cases for dropdown %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown" id="dropdown-color">
              <% if user_signed_in? %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              <% else %>
                <%= link_to 'Sign in', new_user_session_path, class: 'dropdown-item' %>
              <% end %>

            </div>
          </li>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<h1>IS THIS WORKING????</h1>